name = "duran-action-dev"
main = "worker.js"
compatibility_date = "2026-05-29"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
STAGE = "dev"

[env.dev]
name = "duran-action-dev"

[env.dev.vars]
STAGE = "dev"

[env.prod]
name = "duran-action"

[env.prod.vars]
STAGE = "prod"
